### ISSUE TITLE
Declaration error for huge: attempt to use untyped function

### ISSUE THREAD

**Issue by EmanueleSiego** [albertony/f2c#2]
Compiling the following code it gives the error "_Declaration error for huge: attempt to use untyped function_".
```
DOUBLE PRECISION RINF

RINF = HUGE(RINF)
```

**Comment by albertony** [comment]
This needs to be reported to the maintainers of the source code at https://www.netlib.org/f2c/. My project here simply adds build configuration on top of that, and publishes a prebuilt binary, for convenience.
