### ISSUE TITLE
Statement order error: declaration after DATA

### ISSUE THREAD

**Issue by EmanueleSiego** [albertony/f2c#3]
Compiling the following code it gives the error "_Statement order error: declaration after DATA_":
```
CHARACTER*1 PM(-2:2)
DATA PM /'*','-','.','+','.'/
```

**Comment by albertony** [comment]
This needs to be reported to the maintainers of the source code at https://www.netlib.org/f2c/. My project here simply adds build configuration on top of that, and publishes a prebuilt binary, for convenience.
