### ISSUE TITLE
Wrong number of subscripts on variable

### ISSUE THREAD

**Issue by EmanueleSiego** [albertony/f2c#4]
Compiling the following code it gives the errors "_wrong number of subscripts on info_" and "_substring of noncharacter info_":
```
REAL RINFO(20)
REAL ZERO
PARAMETER (ZERO=0.0E0)

RINFO(3:5) = ZERO
```

**Comment by albertony** [comment]
This needs to be reported to the maintainers of the source code at https://www.netlib.org/f2c/. My project here simply adds build configuration on top of that, and publishes a prebuilt binary, for convenience.
